In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/My Drive/csvs/Corona.csv')

In [ ]:
pd.options.display.max_rows = 10
df

     Unnamed: 0 Province/State  ... Latitude Longitude
0             0          Hubei  ...  30.9756  112.2707
1             1            NaN  ...  41.8719   12.5674
2             2            NaN  ...  32.4279   53.6880
3             3            NaN  ...  40.4637   -3.7492
4             4            NaN  ...  51.1657   10.4515
..          ...            ...  ...      ...       ...
271         271            NaN  ...  49.4500   -2.5800
272         272            NaN  ...  49.1900   -2.1100
273         273            NaN  ...  18.2000  -66.5000
274         274            NaN  ...  -1.4400   15.5560
275         275            NaN  ...  31.9522   35.2332

[276 rows x 9 columns]

In [ ]:
#Question One - By default shows first 5
df.head()

   Unnamed: 0 Province/State Country/Region  ... Recovered  Latitude  Longitude
0           0          Hubei          China  ...     56003   30.9756   112.2707
1           1            NaN          Italy  ...      2941   41.8719    12.5674
2           2            NaN           Iran  ...      5389   32.4279    53.6880
3           3            NaN          Spain  ...      1028   40.4637    -3.7492
4           4            NaN        Germany  ...        67   51.1657    10.4515

[5 rows x 9 columns]

In [ ]:
#Question one
df.isnull().sum()
# 150 records out of 276 rows are having Province/State is NULL

Unnamed: 0          0
Province/State    150
Country/Region      0
Last Update         0
Confirmed           0
Deaths              0
Recovered           0
Latitude            0
Longitude           0
dtype: int64

In [ ]:
# Question two
# Calculating the active cases based on the country
df['Active Cases'] = df['Confirmed']-df['Recovered']-df['Deaths']
df

     Unnamed: 0 Province/State  ... Longitude Active Cases
0             0          Hubei  ...  112.2707         8685
1             1            NaN  ...   12.5674        26062
2             2            NaN  ...   53.6880         9792
3             3            NaN  ...   -3.7492        10187
4             4            NaN  ...   10.4515         9166
..          ...            ...  ...       ...          ...
271         271            NaN  ...   -2.5800            0
272         272            NaN  ...   -2.1100            0
273         273            NaN  ...  -66.5000            0
274         274            NaN  ...   15.5560            0
275         275            NaN  ...   35.2332            0

[276 rows x 10 columns]

In [322]:
#Question Three
count_series = df.groupby(['Province/State','Country/Region', 'Last Update']).size()
count_series

Province/State                Country/Region                    Last Update
0                             Afghanistan                       2020-03-17T11:53:10    1
                              Albania                           2020-03-17T15:53:12    1
                              Algeria                           2020-03-17T03:13:15    1
                              Andorra                           2020-03-17T20:53:02    1
                              Antigua and Barbuda               2020-03-15T18:20:19    1
                              Argentina                         2020-03-17T15:53:12    1
                              Armenia                           2020-03-17T19:33:02    1
                              Aruba                             2020-03-17T12:33:07    1
                              Austria                           2020-03-17T15:33:06    1
                              Azerbaijan                        2020-03-17T11:53:10    1
                              Bahrain                           2020-03-17T03:13:15    1
                              Bangladesh                        2020-03-17T12:13:16    1
                              Barbados                          2020-03-17T16:13:14    1
                              Belarus                           2020-03-16T14:38:45    1
                              Belgium                           2020-03-17T15:33:06    1
                              Benin                             2020-03-16T14:38:46    1
                              Bhutan                            2020-03-13T22:22:02    1
                              Bolivia                           2020-03-16T14:38:45    1
                              Bosnia and Herzegovina            2020-03-17T15:53:12    1
                              Brazil                            2020-03-17T15:33:06    1
                              Brunei                            2020-03-17T15:53:12    1
                              Bulgaria                          2020-03-17T10:53:03    1
                              Burkina Faso                      2020-03-16T14:38:45    1
                              Cambodia                          2020-03-17T15:53:13    1
                              Cameroon                          2020-03-17T15:53:13    1
                              Central African Republic          2020-03-16T03:33:03    1
                              Chile                             2020-03-17T15:33:06    1
                              Colombia                          2020-03-17T15:53:12    1
                              Congo (Brazzaville)               2020-03-16T14:38:45    1
                              Congo (Kinshasa)                  2020-03-17T12:33:06    1
                              Costa Rica                        2020-03-17T03:13:15    1
                              Cote d'Ivoire                     2020-03-17T14:33:05    1
                              Croatia                           2020-03-17T10:53:03    1
                              Cuba                              2020-03-17T15:53:13    1
                              Cyprus                            2020-03-17T03:13:15    1
                              Czechia                           2020-03-17T15:33:06    1
                              Dominican Republic                2020-03-17T08:13:22    1
                              Ecuador                           2020-03-17T03:13:15    1
                              Egypt                             2020-03-17T18:13:10    1
                              Equatorial Guinea                 2020-03-15T06:41:54    1
                              Estonia                           2020-03-17T10:33:03    1
                              Eswatini                          2020-03-15T06:41:54    1
                              Ethiopia                          2020-03-16T14:38:45    1
                              Finland                           2020-03-17T12:33:06    1
                              French Guiana                     2020-03-16T14:38:46    1
                              Gabon                             2020-03-14T13:33:04    1
                              Georgia                           2020-03-17T11:13:29    1
                              Germany                           2020-03-17T18:53:02    1
                              Ghana                             2020-03-17T19:33:02    1
                              Greece                            2020-03-17T16:33:04    1
                              Greenland                         2020-03-16T16:53:06    1
                              Guadeloupe                        2020-03-17T10:53:03    1
                              Guam                              2020-03-16T02:13:16    1
                              Guatemala                         2020-03-17T12:13:16    1
                              Guernsey                          2020-03-17T18:33:03    1
                              Guinea                            2020-03-15T06:41:54    1
                              Guyana                            2020-03-17T10:53:03    1
                              Holy See                          2020-03-13T22:22:02    1
                              Honduras                          2020-03-17T12:13:16    1
                              Hungary                           2020-03-17T11:13:29    1
                              Iceland                           2020-03-17T15:33:06    1
                              India                             2020-03-17T15:33:06    1
                              Indonesia                         2020-03-17T10:33:03    1
                              Iran                              2020-03-17T15:13:09    1
                              Iraq                              2020-03-17T15:33:06    1
                              Ireland                           2020-03-17T02:53:03    1
                              Israel                            2020-03-17T20:53:02    1
                              Italy                             2020-03-17T18:33:02    1
                              Jamaica                           2020-03-17T12:13:16    1
                              Japan                             2020-03-17T16:53:04    1
                              Jersey                            2020-03-17T18:33:03    1
                              Jordan                            2020-03-17T11:13:29    1
                              Kazakhstan                        2020-03-17T15:53:12    1
                              Kenya                             2020-03-16T00:22:11    1
                              Korea, South                      2020-03-17T10:33:03    1
                              Kosovo                            2020-03-15T18:20:19    1
                              Kuwait                            2020-03-17T10:53:03    1
                              Latvia                            2020-03-17T11:13:29    1
                              Lebanon                           2020-03-17T10:53:03    1
                              Liberia                           2020-03-17T12:13:16    1
                              Liechtenstein                     2020-03-17T12:13:16    1
                              Lithuania                         2020-03-17T18:53:02    1
                              Luxembourg                        2020-03-17T15:33:06    1
                              Malaysia                          2020-03-17T15:33:06    1
                              Maldives                          2020-03-15T18:20:18    1
                              Malta                             2020-03-17T15:53:12    1
                              Martinique                        2020-03-17T10:53:03    1
                              Mauritania                        2020-03-15T18:20:19    1
                              Mayotte                           2020-03-16T14:38:45    1
                              Mexico                            2020-03-17T10:53:03    1
                              Moldova                           2020-03-17T15:53:12    1
                              Monaco                            2020-03-16T14:38:45    1
                              Mongolia                          2020-03-17T15:53:13    1
                              Montenegro                        2020-03-17T21:33:02    1
                              Morocco                           2020-03-17T15:53:12    1
                              Namibia                           2020-03-14T16:33:03    1
                              Nepal                             2020-03-13T22:22:03    1
                              New Zealand                       2020-03-17T11:53:10    1
                              Nigeria                           2020-03-17T12:33:06    1
                              North Macedonia                   2020-03-17T11:53:10    1
                              Norway                            2020-03-17T19:53:02    1
                              Oman                              2020-03-17T11:53:10    1
                              Pakistan                          2020-03-17T15:33:06    1
                              Panama                            2020-03-17T10:53:03    1
                              Paraguay                          2020-03-17T12:13:16    1
                              Peru                              2020-03-17T15:53:12    1
                              Philippines                       2020-03-17T10:33:03    1
                              Poland                            2020-03-17T20:53:02    1
                              Portugal                          2020-03-17T15:33:06    1
                              Puerto Rico                       2020-03-17T16:13:14    1
                              Qatar                             2020-03-16T15:13:09    1
                              Republic of the Congo             2020-03-17T21:33:03    1
                              Reunion                           2020-03-17T07:15:25    1
                              Romania                           2020-03-17T10:33:03    1
                              Russia                            2020-03-17T15:53:12    1
                              Rwanda                            2020-03-17T02:33:10    1
                              Saint Lucia                       2020-03-17T04:32:19    1
                              Saint Vincent and the Grenadines  2020-03-14T16:33:03    1
                              San Marino                        2020-03-16T01:33:03    1
                              Saudi Arabia                      2020-03-17T17:53:03    1
                              Senegal                           2020-03-17T12:33:06    1
                              Serbia                            2020-03-17T11:13:18    1
                              Seychelles                        2020-03-17T12:33:06    1
                              Singapore                         2020-03-17T15:33:06    1
                              Slovakia                          2020-03-17T02:13:34    1
                              Slovenia                          2020-03-17T16:53:04    1
                              Somalia                           2020-03-16T14:38:46    1
                              South Africa                      2020-03-16T14:38:45    1
                              Spain                             2020-03-17T20:53:02    1
                              Sri Lanka                         2020-03-17T15:53:12    1
                              Sudan                             2020-03-14T01:13:32    1
                              Suriname                          2020-03-14T16:33:03    1
                              Sweden                            2020-03-17T15:33:06    1
                              Switzerland                       2020-03-17T16:33:04    1
                              Taiwan*                           2020-03-17T08:13:11    1
                              Tanzania                          2020-03-17T01:33:03    1
                              Thailand                          2020-03-17T10:33:03    1
                              The Bahamas                       2020-03-16T03:33:03    1
                              The Gambia                        2020-03-17T23:33:02    1
                              Togo                              2020-03-13T22:22:02    1
                              Trinidad and Tobago               2020-03-17T15:53:13    1
                              Tunisia                           2020-03-17T11:53:10    1
                              Turkey                            2020-03-17T22:13:16    1
                              Ukraine                           2020-03-17T19:33:02    1
                              United Arab Emirates              2020-03-16T00:22:11    1
                              Uruguay                           2020-03-17T02:13:54    1
                              Uzbekistan                        2020-03-17T12:13:16    1
                              Venezuela                         2020-03-17T11:33:05    1
                              Vietnam                           2020-03-17T15:53:12    1
                              occupied Palestinian territory    2020-03-11T20:53:02    1
Alabama                       US                                2020-03-17T23:13:10    1
Alaska                        US                                2020-03-17T17:33:03    1
Alberta                       Canada                            2020-03-17T03:13:18    1
Anhui                         China                             2020-03-11T02:18:14    1
Arizona                       US                                2020-03-17T23:13:10    1
Arkansas                      US                                2020-03-16T17:13:23    1
Australian Capital Territory  Australia                         2020-03-16T14:38:46    1
Beijing                       China                             2020-03-17T10:53:03    1
British Columbia              Canada                            2020-03-16T19:13:13    1
California                    US                                2020-03-17T22:53:03    1
Cayman Islands                United Kingdom                    2020-03-16T14:53:04    1
Channel Islands               United Kingdom                    2020-03-16T14:38:45    1
Chongqing                     China                             2020-03-15T03:53:04    1
Colorado                      US                                2020-03-17T22:53:03    1
Connecticut                   US                                2020-03-17T23:13:10    1
Curacao                       Netherlands                       2020-03-17T12:33:07    1
Delaware                      US                                2020-03-17T23:33:02    1
Denmark                       Denmark                           2020-03-17T16:33:04    1
Diamond Princess              Cruise Ship                       2020-03-13T14:13:25    1
                              US                                2020-03-16T16:53:06    1
District of Columbia          US                                2020-03-16T23:53:03    1
Faroe Islands                 Denmark                           2020-03-17T10:13:13    1
Florida                       US                                2020-03-17T23:33:02    1
France                        France                            2020-03-17T19:13:08    1
French Guiana                 France                            2020-03-17T07:33:03    1
French Polynesia              France                            2020-03-15T18:20:19    1
From Diamond Princess         Australia                         2020-03-14T02:33:04    1
Fujian                        China                             2020-03-11T02:18:14    1
Gansu                         China                             2020-03-15T18:20:18    1
Georgia                       US                                2020-03-17T20:13:22    1
Gibraltar                     United Kingdom                    2020-03-17T02:53:03    1
Grand Princess                Canada                            2020-03-17T03:13:18    1
                              US                                2020-03-17T20:53:02    1
Guadeloupe                    France                            2020-03-17T07:33:03    1
Guam                          US                                2020-03-15T18:20:19    1
Guangdong                     China                             2020-03-17T01:53:03    1
Guangxi                       China                             2020-03-17T00:33:02    1
Guizhou                       China                             2020-03-17T07:33:03    1
Hainan                        China                             2020-03-16T14:38:45    1
Hawaii                        US                                2020-03-17T17:33:03    1
Hebei                         China                             2020-03-13T11:09:03    1
Heilongjiang                  China                             2020-03-17T01:33:02    1
Henan                         China                             2020-03-14T09:53:08    1
Hong Kong                     China                             2020-03-17T10:13:11    1
Hubei                         China                             2020-03-17T11:53:10    1
Hunan                         China                             2020-03-14T08:33:03    1
Idaho                         US                                2020-03-17T23:33:02    1
Illinois                      US                                2020-03-17T22:53:03    1
Indiana                       US                                2020-03-17T23:13:10    1
Inner Mongolia                China                             2020-03-16T14:38:45    1
Iowa                          US                                2020-03-16T23:53:03    1
Jiangsu                       China                             2020-03-15T01:53:02    1
Jiangxi                       China                             2020-03-12T02:13:04    1
Jilin                         China                             2020-03-16T00:22:10    1
Kansas                        US                                2020-03-17T23:13:10    1
Kentucky                      US                                2020-03-17T23:33:02    1
Liaoning                      China                             2020-03-17T12:13:13    1
Louisiana                     US                                2020-03-17T22:53:03    1
Macau                         China                             2020-03-17T04:32:18    1
Maine                         US                                2020-03-17T17:53:03    1
Manitoba                      Canada                            2020-03-17T19:33:03    1
Maryland                      US                                2020-03-17T16:13:14    1
Massachusetts                 US                                2020-03-17T22:53:02    1
Mayotte                       France                            2020-03-16T14:38:45    1
Michigan                      US                                2020-03-17T20:53:02    1
Minnesota                     US                                2020-03-17T17:53:03    1
Mississippi                   US                                2020-03-17T17:53:03    1
Missouri                      US                                2020-03-17T23:33:02    1
Montana                       US                                2020-03-17T17:33:03    1
Nebraska                      US                                2020-03-17T17:53:03    1
Netherlands                   Netherlands                       2020-03-17T15:13:11    1
Nevada                        US                                2020-03-17T23:33:02    1
New Brunswick                 Canada                            2020-03-17T19:33:03    1

# As we can see that, the combination of all 3 state, country & last update is just 1, that implies that all data is unique

In [204]:
#Question Three
#Finding unique countries
unique_countries = df["Country/Region"].nunique()
print(unique_countries)

159

In [251]:
#Question Three
#Grouping the countries
pd.options.display.max_rows = 10
DataFrameCountryWise = df[['Country/Region','Confirmed','Recovered','Deaths','Active Cases']].groupby(by=['Country/Region']).sum()
DataFrameCountryWise

                                Confirmed  Recovered  Deaths  Active Cases
Country/Region
Afghanistan                            22          1       0            21
Albania                                55          0       1            54
Algeria                                60         12       4            44
Andorra                                39          1       0            38
Antigua and Barbuda                     1          0       0             1
...                                   ...        ...     ...           ...
Uruguay                                29          0       0            29
Uzbekistan                             10          0       0            10
Venezuela                              33          0       0            33
Vietnam                                66         16       0            50
occupied Palestinian territory          0          0       0             0

[159 rows x 4 columns]

In [249]:
#Question Four
DataFrameCountryWiseStateWise = df[['Country/Region','Province/State','Confirmed','Recovered','Deaths','Active Cases']]
pd.options.display.max_rows = 10
DataFrameCountryWiseStateWise

                     Country/Region Province/State  ...  Deaths  Active Cases
0                             China          Hubei  ...    3111          8685
1                             Italy            NaN  ...    2503         26062
2                              Iran            NaN  ...     988          9792
3                             Spain            NaN  ...     533         10187
4                           Germany            NaN  ...      24          9166
..                              ...            ...  ...     ...           ...
271                        Guernsey            NaN  ...       0             0
272                          Jersey            NaN  ...       0             0
273                     Puerto Rico            NaN  ...       0             0
274           Republic of the Congo            NaN  ...       0             0
275  occupied Palestinian territory            NaN  ...       0             0

[276 rows x 6 columns]

In [241]:
#Question Fifth
#Selecting data which is just from China
chinaData = df.loc[df['Country/Region'] == "China"]
lengthOfChineaseCases = len(chinaData.index)
pd.options.display.max_rows = lengthOfChineaseCases
chinaData

     Unnamed: 0  Province/State  ... Longitude Active Cases
0             0           Hubei  ...  112.2707         8685
12           12       Guangdong  ...  113.4244           49
14           14           Henan  ...  113.6140            1
16           16        Zhejiang  ...  120.0934           15
19           19           Hunan  ...  111.7088            0
20           20           Anhui  ...  117.2264            0
22           22         Jiangxi  ...  115.7221            0
24           24        Shandong  ...  118.1498            8
28           28         Jiangsu  ...  119.4550            0
29           29       Chongqing  ...  107.8740            0
30           30         Sichuan  ...  102.7103           17
31           31    Heilongjiang  ...  127.7615           13
32           32         Beijing  ...  116.4142           79
37           37        Shanghai  ...  121.4491           30
41           41           Hebei  ...  114.5149            2
42           42          Fujian  ...  117.9874            0
46           46         Guangxi  ...  108.7881            3
47           47         Shaanxi  ...  108.8701            7
64           64          Yunnan  ...  101.4870            2
67           67          Hainan  ...  109.7453            1
68           68       Hong Kong  ...  114.2000           70
72           72         Guizhou  ...  106.8748            1
76           76         Tianjin  ...  117.3230            0
77           77           Gansu  ...  103.8343           40
78           78          Shanxi  ...  112.2922            0
80           80        Liaoning  ...  122.6085            4
90           90           Jilin  ...  126.1923            0
95           95        Xinjiang  ...   85.2401            0
96           96  Inner Mongolia  ...  113.9448            1
97           97         Ningxia  ...  106.1655            0
171         171         Qinghai  ...   95.9956            0
179         179           Macau  ...  113.5500            2
247         247           Tibet  ...   88.0924            0

[33 rows x 10 columns]

In [242]:
#Question Fifth
print(lengthOfChineaseCases)

33

In [259]:
#Question Six
df.head(10)

   Unnamed: 0  Province/State  ... Longitude Active Cases
0           0           Hubei  ...  112.2707         8685
1           1             NaN  ...   12.5674        26062
2           2             NaN  ...   53.6880         9792
3           3             NaN  ...   -3.7492        10187
4           4             NaN  ...   10.4515         9166
5           5             NaN  ...  127.7669         6832
6           6          France  ...    2.2137         7492
7           7             NaN  ...    8.2275         2669
8           8  United Kingdom  ...   -3.4360         1843
9           9        New York  ...  -74.9481         1693

[10 rows x 10 columns]

In [253]:
#Question Seven
recoveredData = DataFrameCountryWise.loc[DataFrameCountryWise['Active Cases'] == 0]
recoveredData

                                Confirmed  Recovered  Deaths  Active Cases
Country/Region
Guernsey                                0          0       0             0
Jersey                                  0          0       0             0
Nepal                                   1          1       0             0
Puerto Rico                             0          0       0             0
Republic of the Congo                   0          0       0             0
Sudan                                   1          0       1             0
occupied Palestinian territory          0          0       0             0

In [256]:
#Question Seven
lengthOfrecoveredData = len(recoveredData.index)
print(lengthOfrecoveredData)

7

In [309]:
df.sort_values(by=['Country/Region','Province/State','Last Update'],ascending=[False,False, False])

,Unnamed: 0,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude,Active Cases
275,275,0,occupied Palestinian territory,2020-03-11T20:53:02,0,0,0,31.9522,35.2332,0
110,110,0,Vietnam,2020-03-17T15:53:12,66,0,16,14.0583,108.2772,50
143,143,0,Venezuela,2020-03-17T11:33:05,33,0,0,6.4238,-66.5897,33
191,191,0,Uzbekistan,2020-03-17T12:13:16,10,0,0,41.3775,64.5853,10
149,149,0,Uruguay,2020-03-17T02:13:54,29,0,0,-32.5228,-55.7658,29
8,8,United Kingdom,United Kingdom,2020-03-17T15:13:09,1950,55,52,55.3781,-3.4360,1843
232,232,Gibraltar,United Kingdom,2020-03-17T02:53:03,3,0,1,36.1408,-5.3536,2
212,212,Channel Islands,United Kingdom,2020-03-16T14:38:45,6,0,0,49.3723,-2.3644,6
269,269,Cayman Islands,United Kingdom,2020-03-16T14:53:04,1,1,0,19.3133,-81.2546,0
88,88,0,United Arab Emirates,2020-03-16T00:22:11,98,0,23,23.4241,53.8478,75
177,177,0,Ukraine,2020-03-17T19:33:02,14,2,0,48.3794,31.1656,12
187,187,Wyoming,US,2020-03-17T23:53:03,11,0,0,42.7560,-107.3025,11
102,102,Wisconsin,US,2020-03-17T20:13:22,72,0,1,44.2685,-89.6165,71
268,268,West Virginia,US,2020-03-17T23:33:02,1,0,0,38.4912,-80.9545,1
18,18,Washington,US,2020-03-17T23:33:03,1076,55,1,47.4009,-121.4905,1020
108,108,Virginia,US,2020-03-17T20:13:22,67,2,0,37.7693,-78.1700,65
240,240,Virgin Islands,US,2020-03-17T20:53:02,2,0,0,18.3358,-64.8963,2
182,182,Vermont,US,2020-03-16T17:13:23,12,0,0,44.0459,-72.7107,12
124,124,Utah,US,2020-03-17T20:53:02,51,0,0,40.1500,-111.8624,51
85,85,Texas,US,2020-03-17T20:13:22,110,1,0,31.0545,-97.5635,109
100,100,Tennessee,US,2020-03-17T23:13:10,74,0,0,35.7478,-86.6923,74
186,186,South Dakota,US,2020-03-17T23:33:02,11,1,0,44.2998,-99.4388,10
130,130,South Carolina,US,2020-03-17T23:13:10,47,1,0,33.8569,-80.9450,46
161,161,Rhode Island,US,2020-03-17T20:53:02,23,0,0,41.6809,-71.5118,23
218,218,Puerto Rico,US,2020-03-16T00:22:11,5,0,0,18.2208,-66.5901,5
84,84,Pennsylvania,US,2020-03-17T23:13:10,112,0,0,40.5908,-77.2098,112
109,109,Oregon,US,2020-03-17T23:13:10,66,1,0,44.5720,-122.0709,65
170,170,Oklahoma,US,2020-03-17T17:53:03,19,0,0,35.5653,-96.9289,19
107,107,Ohio,US,2020-03-17T20:53:02,67,0,0,40.3888,-82.7649,67
231,231,North Dakota,US,2020-03-17T23:33:02,3,0,0,47.5289,-99.7840,3
115,115,North Carolina,US,2020-03-17T23:13:10,64,0,0,35.6301,-79.8064,64
9,9,New York,US,2020-03-17T22:53:03,1706,13,0,42.1657,-74.9481,1693
160,160,New Mexico,US,2020-03-17T23:13:10,23,0,0,34.8405,-106.2485,23
44,44,New Jersey,US,2020-03-17T20:13:22,267,3,1,40.2989,-74.5210,263
155,155,New Hampshire,US,2020-03-17T23:13:10,26,0,0,43.4525,-71.5639,26
122,122,Nevada,US,2020-03-17T23:33:02,56,1,0,38.3135,-117.0554,55
168,168,Nebraska,US,2020-03-17T17:53:03,21,0,0,41.1254,-98.2681,21
195,195,Montana,US,2020-03-17T17:33:03,9,0,0,46.9219,-110.4544,9
185,185,Missouri,US,2020-03-17T23:33:02,11,0,0,38.4561,-92.2884,11
167,167,Mississippi,US,2020-03-17T17:53:03,21,0,0,32.7416,-89.6787,21
119,119,Minnesota,US,2020-03-17T17:53:03,60,0,0,45.6945,-93.9002,60
114,114,Michigan,US,2020-03-17T20:53:02,65,0,0,43.3266,-84.5361,65
54,54,Massachusetts,US,2020-03-17T22:53:02,218,0,1,42.2302,-71.5301,217
118,118,Maryland,US,2020-03-17T16:13:14,60,0,3,39.0639,-76.8021,57
144,144,Maine,US,2020-03-17T17:53:03,32,0,0,44.6939,-69.3819,32
59,59,Louisiana,US,2020-03-17T22:53:03,196,4,0,31.1695,-91.8678,192
154,154,Kentucky,US,2020-03-17T23:33:02,26,1,1,37.6681,-84.6701,24
173,173,Kansas,US,2020-03-17T23:13:10,18,1,0,38.5266,-96.7265,17
159,159,Iowa,US,2020-03-16T23:53:03,23,0,0,42.0115,-93.2105,23
147,147,Indiana,US,2020-03-17T23:13:10,30,2,0,39.8494,-86.2583,28
69,69,Illinois,US,2020-03-17T22:53:03,161,1,2,40.3495,-88.9861,158
200,200,Idaho,US,2020-03-17T23:33:02,8,0,0,44.2405,-114.4788,8
190,190,Hawaii,US,2020-03-17T17:33:03,10,0,0,21.0943,-157.4983,10
230,230,Guam,US,2020-03-15T18:20:19,3,0,0,13.4443,144.7937,3
166,166,Grand Princess,US,2020-03-17T20:53:02,21,0,0,37.6489,-122.6655,21
73,73,Georgia,US,2020-03-17T20:13:22,146,1,0,33.0406,-83.6431,145
55,55,Florida,US,2020-03-17T23:33:02,216,6,0,27.7663,-81.6868,210
164,164,District of Columbia,US,2020-03-16T23:53:03,22,0,0,38.8974,-77.0268,22
129,129,Diamond Princess,US,2020-03-16T16:53:06,47,0,0,35.4437,139.6380,47
175,175,Delaware,US,2020-03-17T23:33:02,16,0,0,39.3185,-75.5071,16
105,105,Connecticut,US,2020-03-17T23:13:10,68,0,0,41.5978,-72.7554,68
70,70,Colorado,US,2020-03-17T22:53:03,160,2,0,39.0598,-105.3111,158
25,25,California,US,2020-03-17T22:53:03,698,12,6,36.1162,-119.6816,680
163,163,Arkansas,US,2020-03-16T17:13:23,22,0,0,34.9697,-92.3731,22
169,169,Arizona,US,2020-03-17T23:13:10,20,0,1,33.7298,-111.4312,19
229,229,Alaska,US,2020-03-17T17:33:03,3,0,0,61.3707,-152.4044,3
135,135,Alabama,US,2020-03-17T23:13:10,39,0,0,32.3182,-86.9023,39
128,128,0,Turkey,2020-03-17T22:13:16,47,1,0,38.9637,35.2433,46
158,158,0,Tunisia,2020-03-17T11:53:10,24,0,0,33.8869,9.5375,24
217,217,0,Trinidad and Tobago,2020-03-17T15:53:13,5,0,0,10.6918,-61.2225,5
267,267,0,Togo,2020-03-13T22:22:02,1,0,0,8.6195,0.8248,1
266,266,0,The Gambia,2020-03-17T23:33:02,1,0,0,13.4667,-16.6000,1
265,265,0,The Bahamas,2020-03-16T03:33:03,1,0,0,24.2500,-76.0000,1
63,63,0,Thailand,2020-03-17T10:33:03,177,1,41,15.8700,100.9925,135
264,264,0,Tanzania,2020-03-17T01:33:03,1,0,0,-6.3690,34.8888,1
94,94,0,Taiwan*,2020-03-17T08:13:11,77,1,22,23.7000,121.0000,54
7,7,0,Switzerland,2020-03-17T16:33:04,2700,27,4,46.8182,8.2275,2669
17,17,0,Sweden,2020-03-17T15:33:06,1190,7,1,60.1282,18.6435,1182
263,263,0,Suriname,2020-03-14T16:33:03,1,0,0,3.9193,-56.0278,1
262,262,0,Sudan,2020-03-14T01:13:32,1,1,0,12.8628,30.2176,0
132,132,0,Sri Lanka,2020-03-17T15:53:12,44,0,1,7.8731,80.7718,43
3,3,0,Spain,2020-03-17T20:53:02,11748,533,1028,40.4637,-3.7492,10187
116,116,0,South Africa,2020-03-16T14:38:45,62,0,0,-30.5595,22.9375,62
261,261,0,Somalia,2020-03-16T14:38:46,1,0,0,5.1521,46.1996,1
43,43,0,Slovenia,2020-03-17T16:53:04,275,1,0,46.1512,14.9955,274
101,101,0,Slovakia,2020-03-17T02:13:34,72,0,0,48.6690,19.6990,72
45,45,0,Singapore,2020-03-17T15:33:06,266,0,114,1.3521,103.8198,152
219,219,0,Seychelles,2020-03-17T12:33:06,4,0,0,-4.6796,55.4920,4
113,113,0,Serbia,2020-03-17T11:13:18,65,0,1,44.0165,21.0059,64
153,153,0,Senegal,2020-03-17T12:33:06,26,0,2,14.4974,-14.4524,24
66,66,0,Saudi Arabia,2020-03-17T17:53:03,171,0,6,23.8859,45.0792,165
86,86,0,San Marino,2020-03-16T01:33:03,109,7,4,43.9424,12.4578,98
260,260,0,Saint Vincent and the Grenadines,2020-03-14T16:33:03,1,0,0,12.9843,-61.2872,1
239,239,0,Saint Lucia,2020-03-17T04:32:19,2,0,0,13.9094,-60.9789,2
209,209,0,Rwanda,2020-03-17T02:33:10,7,0,0,-1.9403,29.8739,7
83,83,0,Russia,2020-03-17T15:53:12,114,0,8,61.5240,105.3188,106
62,62,0,Romania,2020-03-17T10:33:03,184,0,16,45.9432,24.9668,168
194,194,0,Reunion,2020-03-17T07:15:25,9,0,0,-21.1151,55.5364,9
274,274,0,Republic of the Congo,2020-03-17T21:33:03,0,0,0,-1.4400,15.5560,0
34,34,0,Qatar,2020-03-16T15:13:09,439,0,4,25.3548,51.1839,435
273,273,0,Puerto Rico,2020-03-17T16:13:14,0,0,0,18.2000,-66.5000,0
33,33,0,Portugal,2020-03-17T15:33:06,448,1,3,39.3999,-8.2245,444
48,48,0,Poland,2020-03-17T20:53:02,238,5,13,51.9194,19.1451,220
60,60,0,Philippines,2020-03-17T10:33:03,187,12,5,12.8797,121.7740,170
82,82,0,Peru,2020-03-17T15:53:12,117,0,1,-9.1900,-75.0152,116
193,193,0,Paraguay,2020-03-17T12:13:16,9,0,0,-23.4425,-58.4438,9
103,103,0,Panama,2020-03-17T10:53:03,69,1,0,8.5380,-80.7821,68
49,49,0,Pakistan,2020-03-17T15:33:06,236,0,2,30.3753,69.3451,234
157,157,0,Oman,2020-03-17T11:53:10,24,0,9,21.4735,55.9754,15
11,11,0,Norway,2020-03-17T19:53:02,1463,3,1,60.4720,8.4689,1459
152,152,0,North Macedonia,2020-03-17T11:53:10,26,0,1,41.6086,21.7453,25
228,228,0,Nigeria,2020-03-17T12:33:06,3,0,0,9.0820,8.6753,3
181,181,0,New Zealand,2020-03-17T11:53:10,12,0,0,-40.9006,174.8860,12
10,10,Netherlands,Netherlands,2020-03-17T15:13:11,1705,43,2,52.1326,5.2913,1660
227,227,Curacao,Netherlands,2020-03-17T12:33:07,3,0,0,12.1696,-68.9900,3
259,259,0,Nepal,2020-03-13T22:22:03,1,0,1,28.3949,84.1240,0
238,238,0,Namibia,2020-03-14T16:33:03,2,0,0,-22.9576,18.4904,2
137,137,0,Morocco,2020-03-17T15:53:12,38,2,1,31.7917,-7.0926,35
237,237,0,Montenegro,2020-03-17T21:33:02,2,0,0,42.5000,19.3000,2
216,216,0,Mongolia,2020-03-17T15:53:13,5,0,0,46.8625,103.8467,5
208,208,0,Monaco,2020-03-16T14:38:45,7,0,0,43.7384,7.4246,7
146,146,0,Moldova,2020-03-17T15:53:12,30,0,1,47.4116,28.3699,29
91,91,0,Mexico,2020-03-17T10:53:03,82,0,4,23.6345,-102.5528,78
258,258,0,Mayotte,2020-03-16T14:38:45,1,0,0,-12.8275,45.1662,1
257,257,0,Mauritania,2020-03-15T18:20:19,1,0,0,21.0079,-10.9408,1
174,174,0,Martinique,2020-03-17T10:53:03,16,1,0,14.6415,-61.0242,15
136,136,0,Malta,2020-03-17T15:53:12,38,0,2,35.9375,14.3754,36
178,178,0,Maldives,2020-03-15T18:20:18,13,0,0,3.2028,73.2207,13
27,27,0,Malaysia,2020-03-17T15:33:06,673,2,49,4.2105,101.9758,622
75,75,0,Luxembourg,2020-03-17T15:33:06,140,1,0,49.8153,6.1296,139
156,156,0,Lithuania,2020-03-17T18:53:02,25,0,1,55.1694,23.8813,24
207,207,0,Liechtenstein,2020-03-17T12:13:16,7,0,0,47.1660,9.5554,7
256,256,0,Liberia,2020-03-17T12:13:16,1,0,0,6.4281,-9.4295,1
81,81,0,Lebanon,2020-03-17T10:53:03,120,3,3,33.8547,35.8623,114
126,126,0,Latvia,2020-03-17T11:13:29,49,0,1,56.8796,24.6032,48
79,79,0,Kuwait,2020-03-17T10:53:03,130,0,9,29.3117,47.4818,121
236,236,0,Kosovo,2020-03-15T18:20:19,2,0,0,42.6026,20.9030,2
5,5,0,"Korea, South",2020-03-17T10:33:03,8320,81,1407,35.9078,127.7669,6832
226,226,0,Kenya,2020-03-16T00:22:11,3,0,0,-0.0236,37.9062,3
142,142,0,Kazakhstan,2020-03-17T15:53:12,33,0,0,48.0196,66.9237,33
140,140,0,Jordan,2020-03-17T11:13:29,34,0,1,30.5852,36.2384,33
272,272,0,Jersey,2020-03-17T18:33:03,0,0,0,49.1900,-2.1100,0
23,23,0,Japan,2020-03-17T16:53:04,878,29,144,36.2048,138.2529,705
180,180,0,Jamaica,2020-03-17T12:13:16,12,0,2,18.1096,-77.2975,10
1,1,0,Italy,2020-03-17T18:33:02,31506,2503,2941,41.8719,12.5674,26062
38,38,0,Israel,2020-03-17T20:53:02,337,0,11,31.0461,34.8516,326
52,52,0,Ireland,2020-03-17T02:53:03,223,2,5,53.1424,-7.6921,216
71,71,0,Iraq,2020-03-17T15:33:06,154,11,32,33.2232,43.6793,111
2,2,0,Iran,2020-03-17T15:13:09,16169,988,5389,32.4279,53.6880,9792
65,65,0,Indonesia,2020-03-17T10:33:03,172,5,8,-0.7893,113.9213,159
74,74,0,India,2020-03-17T15:33:06,142,3,14,20.5937,78.9629,125
53,53,0,Iceland,2020-03-17T15:33:06,220,1,0,64.9631,-19.0208,219
125,125,0,Hungary,2020-03-17T11:13:29,50,1,2,47.1625,19.5033,47
199,199,0,Honduras,2020-03-17T12:13:16,8,0,0,15.2000,-86.2419,8
255,255,0,Holy See,2020-03-13T22:22:02,1,0,0,41.9029,12.4534,1
206,206,0,Guyana,2020-03-17T10:53:03,7,1,0,4.8604,-58.9302,6
254,254,0,Guinea,2020-03-15T06:41:54,1,0,0,9.9456,-9.6966,1
271,271,0,Guernsey,2020-03-17T18:33:03,0,0,0,49.4500,-2.5800,0
211,211,0,Guatemala,2020-03-17T12:13:16,6,1,0,15.7835,-90.2308,5
225,225,0,Guam,2020-03-16T02:13:16,3,0,0,13.4443,144.7937,3
172,172,0,Guadeloupe,2020-03-17T10:53:03,18,0,0,16.2650,-61.5510,18
253,253,0,Greenland,2020-03-16T16:53:06,1,0,0,71.7069,-42.6043,1
36,36,0,Greece,2020-03-17T16:33:04,387,5,8,39.0742,21.8243,374
205,205,0,Ghana,2020-03-17T19:33:02,7,0,0,7.9465,-1.0232,7
4,4,0,Germany,2020-03-17T18:53:02,9257,24,67,51.1657,10.4515,9166
139,139,0,Georgia,2020-03-17T11:13:29,34,0,1,42.3154,43.3569,33
252,252,0,Gabon,2020-03-14T13:33:04,1,0,0,-0.8037,11.6094,1
184,184,0,French Guiana,2020-03-16T14:38:46,11,0,0,3.9339,-53.1258,11
235,235,St Martin,France,2020-03-14T16:33:03,2,0,0,18.0708,-63.0501,2
224,224,Saint Barthelemy,France,2020-03-16T14:38:45,3,0,0,17.9000,-62.8333,3
192,192,Reunion,France,2020-03-17T11:13:29,9,0,0,-21.1351,55.2471,9
251,251,Mayotte,France,2020-03-16T14:38:45,1,0,0,-12.8431,45.1383,1
210,210,Guadeloupe,France,2020-03-17T07:33:03,6,0,0,16.2500,-61.5833,6
223,223,French Polynesia,France,2020-03-15T18:20:19,3,0,0,-17.6797,-149.4068,3
204,204,French Guiana,France,2020-03-17T07:33:03,7,0,0,4.0000,-53.0000,7
6,6,France,France,2020-03-17T19:13:08,7652,148,12,46.2276,2.2137,7492
40,40,0,Finland,2020-03-17T12:33:06,321,0,10,61.9241,25.7482,311
215,215,0,Ethiopia,2020-03-16T14:38:45,5,0,0,9.1450,40.4897,5
250,250,0,Eswatini,2020-03-15T06:41:54,1,0,0,-26.5225,31.4659,1
51,51,0,Estonia,2020-03-17T10:33:03,225,0,1,58.5953,25.0136,224
249,249,0,Equatorial Guinea,2020-03-15T06:41:54,1,0,0,1.5000,10.0000,1
58,58,0,Egypt,2020-03-17T18:13:10,196,4,32,26.8206,30.8025,160
120,120,0,Ecuador,2020-03-17T03:13:15,58,2,0,-1.8312,-78.1834,56
165,165,0,Dominican Republic,2020-03-17T08:13:22,21,1,0,18.7357,-70.1627,20
127,127,Faroe Islands,Denmark,2020-03-17T10:13:13,47,0,0,61.8926,-6.9118,47
21,21,Denmark,Denmark,2020-03-17T16:33:04,977,4,1,56.2639,9.5018,972
35,35,0,Czechia,2020-03-17T15:33:06,396,0,3,49.8175,15.4730,393
131,131,0,Cyprus,2020-03-17T03:13:15,46,0,0,35.1264,33.4299,46
214,214,0,Cuba,2020-03-17T15:53:13,5,0,0,21.5218,-77.7812,5
26,26,Diamond Princess,Cruise Ship,2020-03-13T14:13:25,696,7,325,35.4498,139.6649,364
112,112,0,Croatia,2020-03-17T10:53:03,65,0,4,45.1000,15.2000,61
213,213,0,Cote d'Ivoire,2020-03-17T14:33:05,5,0,1,7.5400,-5.5471,4
133,133,0,Costa Rica,2020-03-17T03:13:15,41,0,0,9.7489,-83.7534,41
222,222,0,Congo (Kinshasa),2020-03-17T12:33:06,3,0,0,-4.0383,21.7587,3
248,248,0,Congo (Brazzaville),2020-03-16T14:38:45,1,0,0,-0.2280,15.8277,1
111,111,0,Colombia,2020-03-17T15:53:12,65,0,1,4.5709,-74.2973,64
16,16,Zhejiang,China,2020-03-17T02:13:21,1232,1,1216,29.1832,120.0934,15
64,64,Yunnan,China,2020-03-16T23:53:02,176,2,172,24.9740,101.4870,2
95,95,Xinjiang,China,2020-03-11T02:18:14,76,3,73,41.1129,85.2401,0
247,247,Tibet,China,2020-03-11T02:18:14,1,0,1,31.6927,88.0924,0
76,76,Tianjin,China,2020-03-15T18:20:18,136,3,133,39.3054,117.3230,0
30,30,Sichuan,China,2020-03-17T08:33:02,540,3,520,30.6171,102.7103,17
78,78,Shanxi,China,2020-03-13T11:09:03,133,0,133,37.5777,112.2922,0
37,37,Shanghai,China,2020-03-17T02:13:20,358,3,325,31.2020,121.4491,30
24,24,Shandong,China,2020-03-17T00:33:02,761,7,746,36.3427,118.1498,8
47,47,Shaanxi,China,2020-03-17T10:53:03,246,3,236,35.1917,108.8701,7
171,171,Qinghai,China,2020-03-11T02:18:14,18,0,18,35.7452,95.9956,0
97,97,Ningxia,China,2020-03-16T14:38:45,75,0,75,37.2692,106.1655,0
179,179,Macau,China,2020-03-17T04:32:18,12,0,10,22.1667,113.5500,2
80,80,Liaoning,China,2020-03-17T12:13:13,125,1,120,41.2956,122.6085,4
90,90,Jilin,China,2020-03-16T00:22:10,93,1,92,43.6661,126.1923,0
22,22,Jiangxi,China,2020-03-12T02:13:04,935,1,934,27.6140,115.7221,0
28,28,Jiangsu,China,2020-03-15T01:53:02,631,0,631,32.9711,119.4550,0
96,96,Inner Mongolia,China,2020-03-16T14:38:45,75,1,73,44.0935,113.9448,1
19,19,Hunan,China,2020-03-14T08:33:03,1018,4,1014,27.6104,111.7088,0
0,0,Hubei,China,2020-03-17T11:53:10,67799,3111,56003,30.9756,112.2707,8685
68,68,Hong Kong,China,2020-03-17T10:13:11,162,4,88,22.3000,114.2000,70
14,14,Henan,China,2020-03-14T09:53:08,1273,22,1250,33.8820,113.6140,1
31,31,Heilongjiang,China,2020-03-17T01:33:02,482,13,456,47.8620,127.7615,13
41,41,Hebei,China,2020-03-13T11:09:03,318,6,310,38.0428,114.5149,2
67,67,Hainan,China,2020-03-16T14:38:45,168,6,161,19.1959,109.7453,1
72,72,Guizhou,China,2020-03-17T07:33:03,147,2,144,26.8154,106.8748,1
46,46,Guangxi,China,2020-03-17T00:33:02,253,2,248,23.8298,108.7881,3
12,12,Guangdong,China,2020-03-17T01:53:03,1364,8,1307,23.3417,113.4244,49
77,77,Gansu,China,2020-03-15T18:20:18,133,2,91,36.0611,103.8343,40
42,42,Fujian,China,2020-03-11T02:18:14,296,1,295,26.0789,117.9874,0
29,29,Chongqing,China,2020-03-15T03:53:04,576,6,570,30.0572,107.8740,0
32,32,Beijing,China,2020-03-17T10:53:03,456,8,369,40.1824,116.4142,79
20,20,Anhui,China,2020-03-11T02:18:14,990,6,984,31.8257,117.2264,0
57,57,0,Chile,2020-03-17T15:33:06,201,0,0,-35.6751,-71.5430,201
246,246,0,Central African Republic,2020-03-16T03:33:03,1,0,0,6.6111,20.9394,1
203,203,Saskatchewan,Canada,2020-03-16T20:13:20,7,0,0,52.9399,-106.4509,7
99,99,Quebec,Canada,2020-03-17T19:33:03,74,0,0,52.9399,-73.5491,74
245,245,Prince Edward Island,Canada,2020-03-15T02:13:21,1,0,0,46.5107,-63.4168,1
61,61,Ontario,Canada,2020-03-17T16:53:04,185,1,5,51.2538,-85.3232,179
202,202,Nova Scotia,Canada,2020-03-17T19:33:03,7,0,0,44.6820,-63.7443,7
221,221,Newfoundland and Labrador,Canada,2020-03-17T17:53:03,3,0,0,53.1355,-57.6604,3
198,198,New Brunswick,Canada,2020-03-17T19:33:03,8,0,0,46.5653,-66.4619,8
197,197,Manitoba,Canada,2020-03-17T19:33:03,8,0,0,53.7609,-98.8139,8
196,196,Grand Princess,Canada,2020-03-17T03:13:18,8,0,0,37.6489,-122.6655,8
87,87,British Columbia,Canada,2020-03-16T19:13:13,103,4,4,53.7267,-127.6476,95
98,98,Alberta,Canada,2020-03-17T03:13:18,74,0,0,53.9333,-116.5765,74
189,189,0,Cameroon,2020-03-17T15:53:13,10,0,0,3.8480,11.5021,10
141,141,0,Cambodia,2020-03-17T15:53:13,33,0,1,12.5657,104.9910,32
176,176,0,Burkina Faso,2020-03-16T14:38:45,15,0,0,12.2383,-1.5616,15
106,106,0,Bulgaria,2020-03-17T10:53:03,67,2,0,42.7339,25.4858,65
121,121,0,Brunei,2020-03-17T15:53:12,56,0,0,4.5353,114.7277,56
39,39,0,Brazil,2020-03-17T15:33:06,321,1,2,-14.2350,-51.9253,318
151,151,0,Bosnia and Herzegovina,2020-03-17T15:53:12,26,0,2,43.9159,17.6791,24
183,183,0,Bolivia,2020-03-16T14:38:45,11,0,0,-16.2902,-63.5887,11
244,244,0,Bhutan,2020-03-13T22:22:02,1,0,0,27.5142,90.4336,1
243,243,0,Benin,2020-03-16T14:38:46,1,0,0,9.3077,2.3158,1
15,15,0,Belgium,2020-03-17T15:33:06,1243,10,1,50.5039,4.4699,1232
138,138,0,Belarus,2020-03-16T14:38:45,36,0,3,53.7098,27.9534,33
234,234,0,Barbados,2020-03-17T16:13:14,2,0,0,13.1939,-59.5432,2
188,188,0,Bangladesh,2020-03-17T12:13:16,10,0,3,23.6850,90.3563,7
50,50,0,Bahrain,2020-03-17T03:13:15,228,1,81,26.0667,50.5577,146
150,150,0,Azerbaijan,2020-03-17T11:53:10,28,1,6,40.1431,47.5769,21
13,13,0,Austria,2020-03-17T15:33:06,1332,3,1,47.5162,14.5501,1328
145,145,Western Australia,Australia,2020-03-17T12:53:09,31,1,0,-31.9505,115.8605,30
89,89,Victoria,Australia,2020-03-17T12:53:09,94,0,8,-37.8136,144.9631,86
201,201,Tasmania,Australia,2020-03-16T14:38:46,7,0,0,-41.4545,145.9707,7
148,148,South Australia,Australia,2020-03-16T14:38:46,29,0,3,-34.9285,138.6007,26
93,93,Queensland,Australia,2020-03-17T12:33:07,78,0,8,-28.0167,153.4000,70
242,242,Northern Territory,Australia,2020-03-14T01:53:03,1,0,0,-12.4634,130.8456,1
56,56,New South Wales,Australia,2020-03-17T12:33:07,210,4,4,-33.8688,151.2093,202
270,270,From Diamond Princess,Australia,2020-03-14T02:33:04,0,0,0,35.4437,139.6380,0
233,233,Australian Capital Territory,Australia,2020-03-16T14:38:46,2,0,0,-35.4735,149.0124,2
220,220,0,Aruba,2020-03-17T12:33:07,3,0,0,12.5211,-69.9683,3
92,92,0,Armenia,2020-03-17T19:33:02,78,0,1,40.0691,45.0382,77
104,104,0,Argentina,2020-03-17T15:53:12,68,2,3,-38.4161,-63.6167,63
241,241,0,Antigua and Barbuda,2020-03-15T18:20:19,1,0,0,17.0608,-61.7964,1
134,134,0,Andorra,2020-03-17T20:53:02,39,0,1,42.5063,1.5218,38
117,117,0,Algeria,2020-03-17T03:13:15,60,4,12,28.0339,1.6596,44
123,123,0,Albania,2020-03-17T15:53:12,55,1,0,41.1533,20.1683,54
162,162,0,Afghanistan,2020-03-17T11:53:10,22,0,1,33.9391,67.7100,21